name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: dotnet test ./tests/TaskManager.Tests/TaskManager.Tests.csproj --configuration Release --no-build --verbosity normal
      
      - name: Publish the project
        run: dotnet publish ./src/TaskManager/TaskManager.csproj --configuration Release --output ./src/TaskManager/bin/Release/net8.0/publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "task-manager-api"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ./src/TaskManager/bin/Release/net8.0/publish
